# Generated by Django 5.0.6 on 2024-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/photos/24/05/12/PfP.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
