# Generated by Django 5.0.6 on 2024-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='PfP.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
