# Generated by Django 5.0.6 on 2024-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile_date_profile_email_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(default=111111111111, max_length=50),
        ),
    ]
