# Generated by Django 5.0.6 on 2024-05-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmPassword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='newPassword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
