# Generated by Django 5.0.6 on 2024-05-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile_confirmpassword_profile_newpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirmPassword',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='newPassword',
        ),
    ]
